import random

# Story prompts - general ideas
STORY_IDEAS = [
    "Write a story about a train ride.",
    "Write a story about an empty house.",
    "Write a story about a map.",
    "Write a story about a locked door.",
    "Write a story about a letter.",
    "Write a story about a photograph.",
    "Write a story about a key.",
    "Write a story about a journey.",
    "Write a story about a storm.",
    "Write a story about a clock.",
    "Write a story about a bridge.",
    "Write a story about a window.",
    "Write a story about a garden.",
    "Write a story about a lighthouse.",
    "Write a story about a road.",
    "Write a story about a fire.",
    "Write a story about a mirror.",
    "Write a story about a coin.",
    "Write a story about a boat.",
    "Write a story about a tower.",
    "Write a story about a forest.",
    "Write a story about a tunnel.",
    "Write a story about a library.",
    "Write a story about a museum.",
    "Write a story about a market.",
    "Write a story about a theater.",
    "Write a story about a hospital.",
    "Write a story about a hotel.",
    "Write a story about a school.",
    "Write a story about a farm.",
    "Write a story about a desert.",
    "Write a story about an island.",
    "Write a story about a cave.",
    "Write a story about a cliff.",
    "Write a story about a river.",
    "Write a story about a border.",
    "Write a story about a wall.",
    "Write a story about a gate.",
    "Write a story about a field.",
    "Write a story about a harbor.",
    "Write a story about a cellar.",
    "Write a story about an attic.",
    "Write a story about a rooftop.",
    "Write a story about a crossroads.",
    "Write a story about a waiting room.",
    "Write a story about a deadline.",
    "Write a story about a reunion.",
    "Write a story about a disappearance.",
    "Write a story about a discovery.",
    "Write a story about a mistake.",
    "Write a story about a secret.",
    "Write a story about a bet.",
    "Write a story about a gift.",
    "Write a story about a theft.",
    "Write a story about a replacement.",
    "Write a story about a competition.",
    "Write a story about an inheritance.",
    "Write a story about a rescue.",
    "Write a story about an escape.",
    "Write a story about a return.",
    "Write a story about a farewell.",
    "Write a story about a beginning.",
    "Write a story about an ending.",
    "Write a story about a trade.",
    "Write a story about a chase.",
    "Write a story about a coincidence.",
    "Write a story about a promise.",
    "Write a story about a lie.",
    "Write a story about a confession.",
    "Write a story about a rumor.",
    "Write a story about a transformation.",
    "Write a story about an obsession.",
    "Write a story about a rivalry.",
    "Write a story about a partnership.",
    "Write a story about a betrayal.",
    "Write a story about a sacrifice.",
    "Write a story about a second chance.",
    "Write a story about a misunderstanding.",
    "Write a story about a lost object.",
    "Write a story about a found object.",
    "Write a story about an unexpected visitor.",
    "Write a story about an unwanted gift.",
    "Write a story about an unanswered question.",
    "Write a story about an unlikely friendship.",
    "Write a story about an old enemy.",
    "Write a story about an old friend.",
    "Write a story about a new neighbor.",
    "Write a story about the last of something.",
    "Write a story about the first of something.",
    "Write a story about something that happens every year.",
    "Write a story about something that only happens once.",
    "Write a story about something that was never supposed to be found.",
    "Write a story about something that refuses to stay buried.",
    "Write a story about something that everyone has forgotten except one person.",
    "Write a story about something that two people remember differently.",
    "Write a story about something that changes hands many times.",
    "Write a story about something that takes a very long time.",
    "Write a story about something that happens too fast.",
]

# Character scenarios
CHARACTER_PROMPTS = [
    "A person wakes up with no memory of the last five years. What do they do first?",
    "Two strangers are stuck in an elevator for three hours. Write their conversation.",
    "A person discovers they can hear the thoughts of animals.",
    "Write about someone who has been keeping a secret for their entire life.",
    "A child finds a door in their house that was never there before.",
    "Write about a person who collects something unusual and why it matters to them.",
    "Someone receives a voicemail from themselves from ten years in the future.",
    "A person who has never lied tells one lie and watches it spiral.",
    "Write about someone who is the last person alive who remembers a certain place.",
    "A character discovers that everything they believed about their past is wrong.",
    "Write about a person who can see how old things are just by touching them.",
    "Two people meet again after thirty years. Neither is who they were.",
    "A character finds out they were supposed to be somewhere else entirely today.",
    "Write about someone who speaks six languages but struggles to say what they mean.",
    "A person keeps finding notes in their own handwriting that they do not remember writing.",
    "Write about a character who is always early and what happens the one time they are late.",
    "A detective realizes mid-case that they know the person who did it.",
    "Write about someone who has been living someone else's life by accident.",
    "A character who has never cried finally does. What breaks them open?",
    "Write about someone who is kind to everyone except themselves.",
    "A person moves to a new city and slowly realizes their neighbor knows them.",
    "Write about a character who always finishes other people's sentences correctly.",
    "Someone finds a diary from their childhood and does not recognize themselves in it.",
    "Write about a person who gives excellent advice but cannot follow any of it.",
    "A character discovers a talent they never knew they had at the worst possible time.",
    "Write about someone who has memorized every exit in every room they enter.",
    "A person who has always been invisible decides to be seen.",
    "Write about a character who is afraid of the one thing they love most.",
    "Two siblings clear out their childhood home and remember it completely differently.",
    "Write about someone who has been waiting for permission that will never come.",
    "A person who has never asked for help finally has to.",
    "Write about a character who is haunted by something they never did.",
    "Someone who has always been the strong one finally falls apart.",
    "Write about a person who cannot stop starting over.",
    "A character says goodbye to something without realizing it is the last time.",
    "Write about someone who lives as though they are always being watched.",
    "A person discovers that the story they tell about themselves is not entirely true.",
    "Write about a character who makes one small choice that changes everything.",
    "Someone who has always been certain suddenly is not.",
    "Write about a person who knows a secret about someone they have never met.",
    "Write about a person who remembers everything but understands very little.",
    "Write about someone who has never once done what was expected of them.",
    "Write about a person who is always the last to know things.",
    "Write about someone who has spent their whole life preparing for something that never came.",
    "Write about a person who is universally liked but privately lonely.",
    "Write about someone who has reinvented themselves so many times they are not sure who they are.",
    "Write about a person who never raises their voice and the one time they do.",
    "Write about someone who has always known exactly what they wanted and suddenly does not.",
    "Write about a person who keeps showing up for people who do not show up for them.",
    "Write about someone who has lived in the same place their entire life and one day sees it differently.",
    "Write about a person who is extremely good at their job and miserable doing it.",
    "Write about someone who has never told the same story the same way twice.",
    "Write about a person who is afraid of getting what they want.",
    "Write about someone who has been carrying someone else's secret for years.",
    "Write about a person who always knows when someone is lying.",
    "Write about someone who has spent years being careful and one day stops.",
    "Write about a person who is defined by something that happened before they were born.",
    "Write about someone who has always been the smartest person in the room and enters a room where they are not.",
    "Write about a person who is generous with everything except the one thing people need most from them.",
    "Write about someone who has been waiting their whole life for an apology that will never come.",
    "Write about a person who makes friends easily and keeps none of them.",
    "Write about someone who has a talent for arriving just after something important happens.",
    "Write about a person who has never needed anyone and suddenly does.",
    "Write about someone who sees the best in everyone except themselves.",
    "Write about a person who has always been defined by their relationship to someone else.",
    "Write about someone who has a gift for saying the wrong thing at the right time.",
    "Write about a person who has been described the same way their entire life and decides to change.",
    "Write about someone who collects other people's problems because it is easier than facing their own.",
    "Write about a person who has always been the responsible one.",
    "Write about someone who has always been the irresponsible one and the day that changes.",
    "Write about a person who speaks very little and is always misunderstood because of it.",
    "Write about someone who speaks a great deal and is always misunderstood because of it.",
    "Write about a person who has a habit of disappearing when things get difficult.",
    "Write about someone who stays when everyone else leaves.",
    "Write about a person who has outlived everyone they love.",
    "Write about someone who has never had to try at anything until now.",
    "Write about a person who has had to try at everything and is tired.",
    "Write about someone who is more comfortable with strangers than with people they know.",
    "Write about a person who has built their life around a single belief that is beginning to crack.",
    "Write about someone who has always been described as difficult and is finally okay with that.",
    "Write about a person who does not know how to accept help.",
    "Write about someone who does not know how to ask for what they need.",
    "Write about a person who has been waiting for their real life to begin.",
    "Write about someone who realized too late that their real life had already been happening.",
    "Write about a person who is terrified of being ordinary.",
    "Write about someone who has spent their whole life trying to be extraordinary and wants to stop.",
    "Write about a person who has always put others first and what happens when they finally do not.",
    "Write about someone who is beloved by everyone who meets them briefly and exhausting to those who know them well.",
    "Write about a person who is quiet about their pain in a world that only notices loud pain.",
    "Write about someone who has always been underestimated and has learned to use it.",
    "Write about a person who has always been overestimated and has learned to hide it.",
    "Write about someone who has devoted their life to something most people do not understand.",
    "Write about a person who has never apologized for anything and the day they have to.",
    "Write about someone who apologizes for everything and decides to stop.",
    "Write about a person who knows exactly how they want to be remembered and whether they are living up to it.",
    "Write about someone who has no idea how they are perceived and finds out.",
    "Write about a person who has always been defined by their ambition.",
    "Write about someone who gave up their ambition and whether they regret it.",
    "Write about a person who is running out of time and the one thing they still need to do.",
    "Write about someone who has all the time in the world and does not know what to do with it.",
    "Write about a person who has always known the right thing to do and for the first time does not.",
    "Write about someone who has rarely done the right thing and decides to start.",
    "Write about a person who is more afraid of hope than of disappointment.",
    "Write about someone who refuses to give up hope no matter what the evidence says.",
    "Write about a person who has spent their whole life in one place imagining another.",
    "Write about someone who has spent their whole life moving and longs to stay somewhere.",
    "Write about a person who has always been described as strong and is finally allowed to be weak.",
    "Write about someone who has always been described as weak and reveals a profound strength.",
    "Write about a person who lives entirely in the past.",
    "Write about someone who refuses to look back under any circumstances.",
    "Write about a person who has a gift for making people feel seen.",
    "Write about someone who has never once felt seen.",
    "Write about a person who is everyone's first call in a crisis.",
    "Write about someone who has never been anyone's first call.",
    "Write about a person who has always been ahead of their time.",
    "Write about someone who has always been behind their time.",
    "Write about a person who carries every version of themselves at once.",
    "Write about someone who has shed every previous version of themselves completely.",
    "Write about a person who is defined by their loyalty.",
    "Write about someone whose loyalty has cost them everything.",
    "Write about a person who has never belonged anywhere.",
    "Write about someone who has always belonged everywhere.",
    "Write about a person who has only ever wanted one thing.",
    "Write about someone who has wanted so many things they have ended up with none of them.",
    "Write about a person who makes everything look effortless.",
    "Write about someone for whom nothing has ever been effortless.",
    "Write about a person who has always been honest to a fault.",
    "Write about someone who has told so many small lies they cannot find the truth anymore.",
    "Write about a person who has been shaped entirely by one relationship.",
    "Write about someone who has refused to be shaped by anyone.",
    "Write about a person who is their own worst enemy.",
    "Write about someone who has finally stopped being their own worst enemy.",
    "Write about a person who has never once doubted themselves.",
    "Write about someone who has never once trusted themselves.",
    "Write about a person who is always the most interesting person in the room and knows it.",
    "Write about someone who is always the most interesting person in the room and does not know it.",
    "Write about a person who has survived something that should have broken them.",
    "Write about someone who was broken by something others survived easily.",
    "Write about a person who has spent their whole life being careful with other people's feelings.",
    "Write about someone who has never learned to be careful with other people's feelings and has to now.",
    "Write about a person who is deeply loved and cannot feel it.",
    "Write about someone who has loved deeply and never been loved back.",
    "Write about a person who has always made the practical choice.",
    "Write about someone who has always made the impractical choice and has no regrets.",
]

# Setting based prompts
SETTING_PROMPTS = [
    "Write a story set in a bookshop that has been in the same family for a hundred years.",
    "Write a story set in a diner at three in the morning.",
    "Write a story set in a waiting room where everyone is waiting for something different.",
    "Write a story set in a lighthouse during the worst storm in decades.",
    "Write a story set in a city where it has not rained in thirty years.",
    "Write a story set in a village that everyone keeps trying to leave.",
    "Write a story set in a hospital where one patient is not supposed to be there.",
    "Write a story set in a school where one classroom is always locked.",
    "Write a story set in a theater on its closing night.",
    "Write a story set in a hotel where the same room is always empty.",
    "Write a story set in a market that only operates one day a year.",
    "Write a story set in a forest that locals will not enter after dark.",
    "Write a story set on a ferry crossing a wide river.",
    "Write a story set in a museum after closing time.",
    "Write a story set in an apartment building where one tenant never leaves.",
    "Write a story set in a small harbor town in winter.",
    "Write a story set in a university library during final exams.",
    "Write a story set in a bakery that opens at four in the morning.",
    "Write a story set in a train station where someone is always saying goodbye.",
    "Write a story set in a town where every building is painted the same color.",
    "Write a story set in a canyon with no phone signal.",
    "Write a story set in a cave system that only one person knows how to navigate.",
    "Write a story set in an old cinema that is about to be torn down.",
    "Write a story set in a village that does not appear on any map.",
    "Write a story set in a community garden in the middle of a city.",
    "Write a story set in a place that used to be something else entirely.",
    "Write a story set in a greenhouse where someone has been sleeping.",
    "Write a story set in a radio station broadcasting to no one.",
    "Write a story set in a town that exists only during one season.",
    "Write a story set in a house that has had thirty different families in fifty years.",
    "Write a story set in a city that rebuilt itself after a disaster.",
    "Write a story set in a neighborhood that is about to change completely.",
    "Write a story set in a place where two countries meet.",
    "Write a story set somewhere so remote that visitors are still talked about years later.",
    "Write a story set in a school of a kind that no longer exists.",
    "Write a story set in a town where no one has left in twenty years.",
    "Write a story set in a library that is open only at night.",
    "Write a story set in a village where the same festival has happened every year for a century.",
    "Write a story set in a city where every street looks identical.",
    "Write a story set in a building that everyone in town has a story about.",
    "Write a story set in a place that floods every spring.",
    "Write a story set in a town with no children.",
    "Write a story set in a place that was once famous and is now forgotten.",
    "Write a story set in a hotel that has been closed for decades and is reopening.",
    "Write a story set in a school that is down to its last few students.",
    "Write a story set in a town where a famous person was born but never returned.",
    "Write a story set in a city that never sleeps and one person who cannot keep up.",
    "Write a story set in a place that exists between two other places.",
    "Write a story set in a building that was never finished.",
    "Write a story set in a town recovering from something no one talks about.",
    "Write a story set in a place that tourists visit but never understand.",
    "Write a story set in a house that has been in the same family for two hundred years.",
    "Write a story set in a neighborhood where everyone knows a secret about one family.",
    "Write a story set in a place that is beautiful in a way that makes people sad.",
    "Write a story set in a city during a blackout.",
    "Write a story set in a small town during its first winter without someone important.",
    "Write a story set in a place that is slowly being abandoned.",
    "Write a story set in a building where people go to be alone.",
    "Write a story set in a port town where ships no longer come.",
    "Write a story set in a valley that gets no sunlight in winter.",
    "Write a story set in a place that changes completely depending on the season.",
    "Write a story set in a town that was built for one purpose and that purpose is gone.",
    "Write a story set in a house that everyone in town has an opinion about.",
    "Write a story set in a place where the same thing happens every year without fail.",
    "Write a story set in a city that is growing too fast.",
    "Write a story set in a village that is shrinking.",
    "Write a story set in a place that two people describe completely differently.",
    "Write a story set in a town where a crime happened long ago that was never solved.",
    "Write a story set in a building that has been many different things over the years.",
    "Write a story set in a place that only the locals know about.",
    "Write a story set in a city on the night before something changes everything.",
    "Write a story set in a town where a stranger arrives every few years and upends things.",
    "Write a story set in a place that is harder to leave than it looks.",
    "Write a story set in a neighborhood that used to be something else.",
    "Write a story set in a house that everyone agrees is wrong somehow.",
    "Write a story set in a place where two rivers meet.",
    "Write a story set in a town that was built around a single industry.",
    "Write a story set in a city district that the rest of the city ignores.",
    "Write a story set in a place that is technically two places at once.",
    "Write a story set in a building that should have been torn down years ago.",
    "Write a story set in a town where the same family has run everything for generations.",
    "Write a story set in a place that looks one way from the outside and another from within.",
    "Write a story set in a neighborhood during its last summer before demolition.",
    "Write a story set in a city that was built over something older.",
    "Write a story set in a place where people go to disappear.",
    "Write a story set in a village where outsiders are rare.",
    "Write a story set in a house that has passed through many hands quickly.",
    "Write a story set in a place that is exactly the same as it was fifty years ago.",
    "Write a story set in a town that exists mainly in the memories of people who have left.",
    "Write a story set in a city where one street is completely different from the rest.",
    "Write a story set in a place that was built for people who never came.",
    "Write a story set in a building where people have been working for decades without meeting.",
    "Write a story set in a town where everyone arrived from somewhere else.",
    "Write a story set in a place that is only accessible part of the year.",
    "Write a story set in a neighborhood where everyone is waiting for something.",
    "Write a story set in a city during a heatwave.",
    "Write a story set in a town during its annual fair.",
    "Write a story set in a place that has been argued over for generations.",
    "Write a story set in a building that everyone walks past but no one enters.",
    "Write a story set in a town where the same argument has been going on for decades.",
    "Write a story set in a place that was once dangerous and is now safe.",
    "Write a story set in a place that was once safe and is no longer.",
    "Write a story set in a city on the day of an election.",
    "Write a story set in a town that has one of everything.",
    "Write a story set in a place that floods the memories of everyone who visits.",
    "Write a story set in a house that smells like someone who is no longer there.",
    "Write a story set in a town where everyone has the same last name.",
    "Write a story set in a place that does not welcome visitors.",
    "Write a story set in a building that hums with something no one can explain.",
    "Write a story set in a city where one district has been frozen in time.",
    "Write a story set in a place that everyone has strong feelings about.",
    "Write a story set in a town that has produced an unusual number of a certain kind of person.",
    "Write a story set in a place that is far more interesting than it appears.",
    "Write a story set in a building that everyone agrees has a particular feeling.",
    "Write a story set in a neighborhood on the night of a block party.",
    "Write a story set in a place that is someone's whole world.",
    "Write a story set in a city that has reinvented itself many times.",
    "Write a story set in a house that was built by someone with strong opinions.",
    "Write a story set in a town that is famous for something its residents find embarrassing.",
    "Write a story set in a place that people return to again and again without knowing why.",
    "Write a story set in a building that was designed for something it has never been used for.",
    "Write a story set in a town on the day its last institution closes.",
    "Write a story set in a place that is technically no one's responsibility.",
    "Write a story set in a city where two very different worlds share the same street.",
    "Write a story set in a house on the last night before it is sold.",
    "Write a story set in a place that means different things to different generations.",
    "Write a story set in a town that attracts a particular kind of person.",
    "Write a story set in a building that has its own set of unwritten rules.",
    "Write a story set in a place that has outlasted everything around it.",
    "Write a story set in a city on the morning after something significant.",
    "Write a story set in a neighborhood that has a complicated history.",
    "Write a story set in a place where the past is more present than the present.",
    "Write a story set in a town where everyone has a theory about why it exists.",
    "Write a story set in a building at the moment it is finally finished.",
    "Write a story set in a place that is about to become something else entirely.",
]

# Object based prompts
OBJECT_PROMPTS = [
    "An old photograph falls out of a used book. Write the story behind it.",
    "Write about an object that has been passed down through generations.",
    "Someone finds a journal that does not belong to them. What is inside?",
    "Write about the last object a person would ever give away.",
    "Write about an object that meant everything to someone and nothing to everyone else.",
    "A box is found in an attic with no explanation of where it came from.",
    "Write about a piece of clothing that carries a memory.",
    "Someone receives a package addressed to a name they do not recognize.",
    "Write about an object that two people remember completely differently.",
    "A watch stops working the moment its owner dies. Years later it starts again.",
    "Write about a chair that has been in the same spot for decades.",
    "Someone throws something away and immediately regrets it.",
    "Write about an object that was never supposed to survive.",
    "A ring is found on a beach. Write about how it got there.",
    "Write about a toy that outlasted everything around it.",
    "Someone keeps an object that brings them pain. Why won't they let it go?",
    "Write about a tool that has been used every day for thirty years.",
    "A door key no longer fits the lock it was made for.",
    "Write about a book so loved it is falling apart.",
    "An instrument that has not been played in years is taken out of its case.",
    "Write about an object that was found at the scene of something unexplained.",
    "Someone inherits a collection they know nothing about.",
    "Write about an object that two strangers both claim to own.",
    "A child's drawing is found inside the walls of an old house.",
    "Write about an object that everyone in a family has an opinion about.",
    "Something ordinary is found to have an extraordinary history.",
    "Write about an object that has traveled further than any person who owned it.",
    "A suitcase is left at a train station and never claimed.",
    "Write about an object that was made for one purpose and used for another.",
    "Someone discovers that an object they own is worth far more than they thought.",
]

# Journaling prompts
JOURNAL_PROMPTS = [
    "What is something you are carrying right now that you need to put down?",
    "Describe a version of yourself from five years ago. What would surprise them?",
    "What does your ideal ordinary day look like, in detail?",
    "Write about a person who shaped who you are without knowing it.",
    "What is something you have never told anyone, and why?",
    "Describe a moment when everything felt exactly right.",
    "What are you most afraid of losing?",
    "Write a letter to someone you will never be able to send it to.",
    "What is a belief you held strongly that you no longer hold? What changed?",
    "Describe your relationship with silence.",
    "What does home mean to you right now, in this moment?",
    "Write about something small that brings you genuine happiness.",
    "What would you do with one completely free, obligation-free day?",
    "Write about a time when you surprised yourself.",
    "What is something you are still learning about yourself?",
    "What would the ten-year-old version of you think of your life right now?",
    "Write about a relationship that changed you.",
    "What does rest mean to you, and do you allow yourself to have it?",
    "Write about something you have outgrown.",
    "What do you want more of in your life, and what is stopping you?",
    "Write about a time when you felt most like yourself.",
    "What are you pretending not to know?",
    "Write about a habit you have that you cannot explain.",
    "What would you do differently if no one was watching?",
    "Write about something you are proud of that you never talk about.",
    "What does a good day look like for you, really?",
    "Write about a fear that has shrunk over time and how that happened.",
    "What is something you keep meaning to do that you have not done yet?",
    "Write about a person you miss.",
    "What are you grateful for that you rarely acknowledge?",
    "Write about something you wish someone had told you earlier.",
    "What part of yourself do you find hardest to accept?",
    "Write about a moment when you felt genuinely free.",
    "What does success mean to you now versus what it meant before?",
    "Write about something that is harder for you than it seems to be for others.",
    "What do you need right now that you are not giving yourself?",
    "Write about a version of your future self you are working toward.",
    "What is one thing you would tell yourself a year ago?",
    "Write about something you have made peace with.",
    "What is something you do purely for yourself, with no other reason?",
    "Write about a time when you chose comfort over growth. Do you regret it?",
    "What would your life look like if you stopped being afraid?",
    "Write about something that used to hurt that no longer does.",
    "What is a question you keep coming back to?",
    "Write about the gap between who you are and who you want to be.",
    "What would you do if you knew you could not fail?",
    "Write about a moment when you felt truly seen.",
    "What is something you are still figuring out?",
    "Write about the last time you changed your mind about something important.",
    "What does your inner critic sound like, and where did it come from?",
    "What is a version of yourself you have had to leave behind?",
    "Write about something you do when no one is watching.",
    "What is the most important thing you have learned in the last year?",
    "Write about a place that exists only in your memory now.",
    "What is something you have been avoiding thinking about?",
    "Write about a time when you felt completely at peace.",
    "What is something you wish you could unlearn?",
    "Write about a person you have never properly thanked.",
    "What is something you do that your younger self would not understand?",
    "Write about a time when you felt like you were exactly where you were supposed to be.",
    "What is something you have changed your mind about recently?",
    "Write about a time when you felt misunderstood.",
    "What is something you are better at than you give yourself credit for?",
    "Write about a moment when you realized you had become someone different.",
    "What is something you have been meaning to let go of?",
    "Write about a time when you did something that scared you.",
    "What is a dream you have given up on, and how do you feel about that?",
    "Write about a time when you felt genuinely proud of yourself.",
    "What is something you wish you had more patience for?",
    "Write about a conversation you keep replaying in your head.",
    "What is something you have inherited from your parents that you wish you hadn't?",
    "Write about a time when you felt ahead of yourself.",
    "What is something you have inherited from your parents that you are grateful for?",
    "Write about a time when you felt behind everyone else.",
    "What is something that has taken you longer to learn than it should have?",
    "Write about a time when you asked for too little.",
    "What is something you have never given yourself permission to want?",
    "Write about a time when you asked for too much.",
    "What does your relationship with money say about you?",
    "Write about a time when you felt genuinely generous.",
    "What is something you do out of habit that no longer serves you?",
    "Write about a time when you were the one who needed rescuing.",
    "What is something you have tried to change about yourself that never stuck?",
    "Write about a time when you were in the right place at the right time.",
    "What is something you have accepted about yourself that used to bother you?",
    "Write about a time when you felt like a different person than you are now.",
    "What is something you regret not saying sooner?",
    "Write about a time when you were more resilient than you expected.",
    "What is a story you tell about yourself that might not be entirely true?",
    "Write about a time when you were wrong about someone.",
    "What is something that makes you feel alive?",
    "Write about a time when you felt numb.",
    "What is something you are curious about that you have never pursued?",
    "Write about a time when you felt completely out of your depth.",
    "What is something you have done that you are genuinely proud of but rarely mention?",
    "Write about a time when you felt like you belonged.",
    "What is something you carry from your childhood that still affects you?",
    "Write about a time when you felt like you did not belong.",
    "What is something you have sacrificed that you are not sure was worth it?",
    "Write about a time when you received advice you ignored and should not have.",
    "What is something you have sacrificed that was absolutely worth it?",
    "Write about a time when you received advice you followed and should not have.",
    "What does your morning routine say about who you are?",
    "Write about a time when you felt completely overwhelmed.",
    "What does your evening routine say about who you are?",
    "Write about a time when you felt completely calm.",
    "What is something you have never admitted to wanting?",
    "Write about a time when you had to start over.",
    "What is something you wish you could go back and experience again?",
    "Write about a time when someone believed in you before you believed in yourself.",
    "What is something you wish you could go back and skip entirely?",
    "Write about a time when you had to choose between two things you loved.",
    "What is something you are still angry about?",
    "Write about a time when anger taught you something.",
    "What is something you have forgiven that surprised you?",
    "Write about a time when forgiveness was harder than you expected.",
    "What is something you have not yet forgiven?",
    "Write about a time when you were at your worst.",
    "What is something you have not yet forgiven yourself for?",
    "Write about a time when you were at your best.",
    "What is something that brings you comfort that you rarely talk about?",
    "Write about a time when you felt completely lost.",
    "What is something you have learned from failure?",
    "Write about a time when you felt completely found.",
    "What is something you have learned from someone younger than you?",
    "Write about a time when you had to be someone's anchor.",
    "What is something you have learned from someone much older than you?",
    "Write about a time when you needed someone to be your anchor.",
    "What is something you do that connects you to who you used to be?",
    "Write about a time when you felt the most creative.",
    "What is something you have stopped doing that you miss?",
    "Write about a time when you felt the least creative.",
    "What is something you have started doing that you are glad you did?",
    "Write about a time when you felt completely content.",
    "What is something you wish you had started sooner?",
    "Write about a time when contentment felt out of reach.",
    "What is something you have let define you that you should not have?",
    "Write about a time when you felt misplaced in time.",
    "What is something you have refused to let define you?",
    "Write about a time when music changed your mood entirely.",
    "What is something you know about yourself that most people do not?",
    "Write about a time when being alone felt like relief.",
    "What is something others know about you that you have trouble seeing yourself?",
    "Write about a time when being alone felt unbearable.",
    "What is something you are more sensitive about than you let on?",
    "Write about a time when you felt genuinely hopeful.",
    "What is something you have numbed yourself to that you probably should not have?",
    "Write about a time when hope felt impossible.",
    "What is something you wish you could ask someone who is no longer here?",
    "Write about a time when you felt like you were enough.",
    "What is something you have been told about yourself that you have never believed?",
    "Write about a time when you felt like you were not enough.",
    "What is something you have been told about yourself that turned out to be true?",
    "Write about a time when you showed up for someone in a way that mattered.",
    "What is something you wish someone would ask you about?",
    "Write about a time when someone showed up for you in a way that mattered.",
    "What is something you have been putting off that has nothing to do with time?",
    "Write about a time when you felt the weight of other people's expectations.",
    "What is something you do just because it makes you happy, with no other reason?",
    "Write about a time when you freed yourself from an expectation.",
    "What is a dream you still have that you have not told anyone?",
    "Write about a time when your body told you something your mind ignored.",
    "What is something you wish you were better at accepting?",
    "Write about a time when you listened to your instincts and were right.",
    "What is something you need to hear right now?",
    "Write about a time when you ignored your instincts and were wrong.",
    "What is something that has surprised you about getting older?",
    "Write about a time when you felt young in a way that had nothing to do with age.",
    "What is something that has disappointed you about getting older?",
    "Write about a time when age felt like a gift.",
    "What is something you want to remember about this period of your life?",
    "Write about a time when you felt like time was standing still.",
    "What is something you are afraid to want because you are afraid you will not get it?",
    "Write about a time when time moved too fast.",
    "What is something you would do differently if you were not afraid of what people think?",
    "Write about a time when you stopped caring what people thought.",
    "What is something you have never done alone that you want to try?",
    "Write about a time when you realized you had been holding your breath.",
    "What is something you would tell your future self?",
    "Write about a time when everything felt uncertain and you were okay.",
    "What is something you are ready for that you have not admitted yet?",
    "Write about a time when you realized you were not as alone as you thought.",
    "What is something you are not ready for that you know is coming?",
    "Write about a time when a small thing made a big difference.",
    "What is something that grounds you when everything feels like too much?",
    "Write about a time when you chose peace over being right.",
    "What is something you are learning to need less of?",
    "Write about a time when you chose being right over peace.",
    "What is something you are learning to need more of?",
    "Write about a time when you realized what actually mattered.",
    "What is something you have always wanted to write about but have not?",
    "Write about a time when you had everything you needed.",
    "What does your relationship with your own needs say about you?",
    "Write about a time when you went without something important.",
    "What is something you are still becoming?",
    "Write about a time when you felt like you were finally arriving.",
    "What is something that has stayed constant in your life through everything?",
    "Write about a time when everything changed at once.",
    "What is something that deserves more of your attention than it gets?",
    "Write about a time when you had to reimagine your future.",
    "What is something you are thankful for that was once painful?",
    "Write about a time when the future felt wide open.",
    "What is something you have done that took more courage than anyone knew?",
    "Write about a time when the future felt closed off.",
    "What is something you would do today if you knew it was your last ordinary day?",
    "Write about a time when ordinary life felt extraordinary.",
    "What is something about yourself that has never changed?",
    "Write about a time when you felt like the truest version of yourself.",
    "What is something you want to stop pretending about?",
    "Write about a time when pretending kept you safe.",
    "What is something you want to be remembered for?",
    "Write about a time when you were not remembered and it hurt.",
    "What is something you are still healing from?",
    "Write about a time when you realized you had healed.",
    "What is something you want more space for in your life?",
    "Write about a time when you had exactly the right amount of space.",
    "What is something you are done apologizing for?",
    "Write about a time when an apology changed everything.",
    "What is something you want to pursue before you talk yourself out of it?",
    "Write about a time when you talked yourself into something important.",
    "What is something you have learned about love?",
    "Write about a time when love surprised you.",
    "What is something you have learned about loss?",
    "Write about a time when loss gave you something unexpected.",
    "What is something you know now that you wish you had known at the beginning?",
    "Write about a time when not knowing turned out to be a gift.",
    "What is something you want to say yes to more often?",
    "Write about a time when saying yes changed everything.",
    "What is something you want to say no to more often?",
    "Write about a time when saying no was the right thing.",
    "What is something that has made you who you are that had nothing to do with you?",
    "Write about a time when circumstances shaped you in ways you are still discovering.",
    "What is something you are choosing, right now, to believe about yourself?",
    "Write about a time when you chose to believe something different and it changed you.",
]

# Emotional prompts
EMOTIONAL_PROMPTS = [
    "Write about a moment when you realized someone had changed.",
    "Write about the feeling of leaving a place you loved for the last time.",
    "Write about a decision that still stays with you.",
    "Write about a moment of unexpected kindness from a stranger.",
    "Write about something you wish you had said.",
    "Write about a time when being wrong turned out to be the best thing.",
    "Write about a moment when you felt completely understood.",
    "Write about the last time you were truly surprised.",
    "Write about a time when you stayed when you should have left.",
    "Write about a moment that felt insignificant then but matters now.",
    "Write about the first time you realized an adult you trusted was wrong.",
    "Write about a moment when you chose yourself.",
    "Write about a time when silence said more than words.",
    "Write about the moment a friendship shifted into something else.",
    "Write about a time you were a stranger somewhere and what that felt like.",
    "Write about a moment of grief that caught you off guard.",
    "Write about a time when you had to let something go.",
    "Write about the last time you felt like a child.",
    "Write about a moment that redefined what courage meant to you.",
    "Write about a time when you changed your mind about a person.",
    "Write about the moment you realized something was ending.",
    "Write about a time when the right thing and the easy thing were not the same.",
    "Write about a moment of pure, uncomplicated joy.",
    "Write about a time you felt invisible.",
    "Write about something you are still grieving.",
    "Write about a moment when fear kept you from something important.",
    "Write about the last time you asked for forgiveness.",
    "Write about a time when you felt out of place in your own life.",
    "Write about a moment when everything you thought you knew shifted.",
    "Write about the feeling of waiting for news you are not sure you want.",
    "Write about a time when you were kinder than you felt.",
    "Write about a moment when you realized you were not alone.",
    "Write about something that broke you open in a good way.",
    "Write about a time when you had to be brave without anyone knowing it.",
    "Write about a moment when you understood something about your parents.",
    "Write about a time when laughter came at exactly the wrong moment.",
    "Write about a moment when you felt the weight of time.",
    "Write about something you did out of love that no one ever knew about.",
    "Write about a time when you held on too long.",
    "Write about a moment when you realized you had grown up.",
]

# Combined story prompts for the Story menu
STORY_PROMPTS = STORY_IDEAS + CHARACTER_PROMPTS + SETTING_PROMPTS + OBJECT_PROMPTS

# Combined journal prompts for the Journal menu
JOURNALING_PROMPTS = JOURNAL_PROMPTS + EMOTIONAL_PROMPTS


def get_story_prompt():
    # Return a randomly selected story prompt
    return random.choice(STORY_PROMPTS)


def get_journal_prompt():
    # Return a randomly selected journal prompt
    return random.choice(JOURNALING_PROMPTS)